function window1
    % ── Missile categories ────────────────────────────────────────────
    missile_data = { ...
        'Short-Range Ballistic Missile (SRBM)'; ...
        'Medium-Range Ballistic Missile (MRBM)'; ...
        'Intermediate-Range Ballistic Missile (IRBM)'; ...
        'Intercontinental Ballistic Missile (ICBM)'; ...
    };

    % ── Colour palette ────────────────────────────────────────────────
    C.bg        = [0.08 0.10 0.13];   % near-black background
    C.panel     = [0.11 0.14 0.18];   % slightly lighter panels
    C.accent    = [0.95 0.65 0.10];   % amber accent
    C.text      = [0.90 0.92 0.95];   % off-white text
    C.sub       = [0.50 0.55 0.62];   % muted sub-text
    C.border    = [0.20 0.26 0.33];   % panel border colour
    C.hover     = [0.14 0.18 0.24];   % listbox selection bg
    C.btnGo     = [0.18 0.55 0.34];   % green action button
    C.red       = [0.85 0.22 0.22];   % alert / danger

    % ── Figure ───────────────────────────────────────────────────────
    fig1 = uifigure( ...
        'Name',     'BMDS — Ballistic Missile Category Selection', ...
        'Position', [200 180 680 480], ...
        'Color',    C.bg, ...
        'Resize',   'on');

    % ── Top header bar ───────────────────────────────────────────────
    uipanel(fig1, ...
        'Position',         [0 440 680 40], ...
        'BackgroundColor',  C.accent, ...
        'BorderType',       'none');

    uilabel(fig1, ...
        'Text',         '⬡  BMDS  |  BALLISTIC MISSILE DEFENSE SYSTEM', ...
        'Position',     [20 444 500 28], ...
        'FontSize',     10, ...
        'FontWeight',   'bold', ...
        'FontColor',    C.bg);

    uilabel(fig1, ...
        'Text',         'CLASSIFICATION: TOP SECRET', ...
        'Position',     [490 444 180 28], ...
        'FontSize',     9, ...
        'FontWeight',   'bold', ...
        'FontColor',    [0.15 0.08 0.02], ...
        'HorizontalAlignment', 'right');

    % ── Left decorative strip ─────────────────────────────────────────
    uipanel(fig1, ...
        'Position',         [0 0 4 440], ...
        'BackgroundColor',  C.accent, ...
        'BorderType',       'none');

    % ── Section title ─────────────────────────────────────────────────
    uilabel(fig1, ...
        'Text',         'STEP 1  —  SELECT MISSILE CATEGORY', ...
        'Position',     [30 388 500 30], ...
        'FontSize',     15, ...
        'FontWeight',   'bold', ...
        'FontColor',    C.accent);

    uilabel(fig1, ...
        'Text',         'Choose the operational range class before selecting a specific rocket.', ...
        'Position',     [30 363 600 20], ...
        'FontSize',     10, ...
        'FontColor',    C.sub);

    % ── Thin divider line ─────────────────────────────────────────────
    uipanel(fig1, ...
        'Position',         [30 358 620 1], ...
        'BackgroundColor',  C.border, ...
        'BorderType',       'none');

    % ── Category cards (one per missile class) ───────────────────────
    card_labels = missile_data;
    card_desc   = { ...
        'Range < 1,000 km  ·  Tactical theatre role', ...
        'Range 1,000 – 3,500 km  ·  Regional strike', ...
        'Range 3,500 – 5,500 km  ·  Extended regional', ...
        'Range > 5,500 km  ·  Strategic intercontinental' ...
    };
    icons = {'▸', '▸▸', '▸▸▸', '▸▸▸▸'};

    card_y = [270 220 170 120];   % y positions for the four cards

    for k = 1:4
        % card background
        uipanel(fig1, ...
            'Position',         [30 card_y(k) 620 42], ...
            'BackgroundColor',  C.panel, ...
            'BorderType',       'line', ...
            'HighlightColor',   C.border);

        % icon
        uilabel(fig1, ...
            'Text',         icons{k}, ...
            'Position',     [44 card_y(k)+10 30 22], ...
            'FontSize',     11, ...
            'FontColor',    C.accent);

        % main label
        uilabel(fig1, ...
            'Text',         card_labels{k}, ...
            'Position',     [80 card_y(k)+18 400 18], ...
            'FontSize',     11, ...
            'FontWeight',   'bold', ...
            'FontColor',    C.text);

        % description
        uilabel(fig1, ...
            'Text',         card_desc{k}, ...
            'Position',     [80 card_y(k)+4 420 14], ...
            'FontSize',     9, ...
            'FontColor',    C.sub);
    end

    % ── Listbox (hidden but functional for value capture) ─────────────
    lb = uilistbox(fig1, ...
        'Items',            missile_data, ...
        'Position',         [30 120 620 196], ...  % overlaps cards exactly
        'FontSize',         11, ...
        'BackgroundColor',  [0 0 0 ], ...
        'FontColor',        [0 0 0], ...
        'Value',            missile_data{1});
    lb.BackgroundColor  = [0 0 0];      % fully transparent trick
    lb.FontColor        = [0 0 0];

    % Make the listbox transparent by matching bg — reuse same region
    % Re-create a visible, styled listbox layered on top of cards
    lb2 = uilistbox(fig1, ...
        'Items',            missile_data, ...
        'Position',         [30 120 620 196], ...
        'FontSize',         12, ...
        'BackgroundColor',  [0.00 0.00 0.00 ], ...
        'FontColor',        C.text);
    % We'll actually use lb2 only; match style to look like card selector
    lb2.BackgroundColor = [0.09 0.12 0.16];
    lb2.FontColor       = C.text;

    % ── Progress indicator ────────────────────────────────────────────
    uilabel(fig1, ...
        'Text',         '● STEP 1 of 3', ...
        'Position',     [30 88 200 18], ...
        'FontSize',     9, ...
        'FontColor',    C.accent);

    uilabel(fig1, ...
        'Text',         '○ STEP 2  ○ STEP 3', ...
        'Position',     [130 88 200 18], ...
        'FontSize',     9, ...
        'FontColor',    C.sub);

    % ── Action button ─────────────────────────────────────────────────
    btn = uibutton(fig1, ...
        'Text',             '  PROCEED TO ROCKET SELECTION  ›', ...
        'Position',         [440 50 220 38], ...
        'FontSize',         11, ...
        'FontWeight',       'bold', ...
        'BackgroundColor',  C.btnGo, ...
        'FontColor',        'white');

    btn.ButtonPushedFcn = @(~,~) window2(lb2.Value);

    % ── Bottom status bar ─────────────────────────────────────────────
    uipanel(fig1, ...
        'Position',         [0 0 680 40], ...
        'BackgroundColor',  [0.06 0.08 0.10], ...
        'BorderType',       'none');

    uilabel(fig1, ...
        'Text',         'SYSTEM READY  |  AWAITING OPERATOR INPUT', ...
        'Position',     [20 10 400 20], ...
        'FontSize',     9, ...
        'FontColor',    C.sub);

    uilabel(fig1, ...
        'Text',         'v2.1.0  |  © BMDS PLATFORM', ...
        'Position',     [510 10 160 20], ...
        'FontSize',     9, ...
        'FontColor',    C.border, ...
        'HorizontalAlignment', 'right');
end